### PR TITLE
Adding Client Server example

### PR DESCRIPTION
**Pull request by IMAN4K**
Signed-off-by: Iman Ahmadvand iman72411@gmail.com (github: @IMAN4K)

### CODE REVIEW

**Comment by romansavrulin** [comment]
@IMAN4K please rename `ClientServer/client.ino` to `ClientServer/ClientServer.ino` so Travis could proceed

**Comment by hreintke** [comment]
Hi,

I think in examples one should use Library options and not direct SDK calls.

-> Ticker instead of os_timer_t

**Comment by IMAN4K** [comment]
@hreintke 
That's fine.
This is just an example with focus on `TCP` not the timing.
Anyone could pick whatever they prefer.
Anyway, you can commit after example get pushed to master.

**Comment by romansavrulin** [comment]
@IMAN4K , please take a look at [Travis job output](https://travis-ci.org/me-no-dev/ESPAsyncTCP/builds/326296473?utm_source=github_status&utm_medium=notification)

Seems like it tries to compile both `ClientServer.ino` and `server.ino` in the same pass. The reason, as I can see is the arduino sketch layout rules. `.ino` files are per-project, and should be the one and the only in the project directory and has the same name as the directory.

Could you please separate client and server examples to different folders?

Please note, if you have common configuration to both project (e.g. `config.h`) you should copy it to both folders too.

**Comment by IMAN4K** [comment]
@romansavrulin 

> The reason, as I can see is the arduino sketch layout rules. .ino files are per-project, and should be the one and the only in the project directory and has the same name as the directory

That's an odd thing! i was thinking for sketch as C++ source since they're using `GCC` as tool-chain for Arduino.
I'll modify it.

**Comment by IMAN4K** [comment]
@romansavrulin 

> The reason, as I can see is the arduino sketch layout rules. .ino files are per-project, and should be the one and the only in the project directory and has the same name as the directory

That's an odd thing! i was thinking sketch as C++ source file since they're using `GCC` as tool-chain.
I'll modify it.

**Comment by romansavrulin** [comment]
@IMAN4K, for sure. I'm suffering a lot from it too. But while you are compiling with GCC in Arduino, you should play the rules Arduino guys decided to use to manage includes and other stuff.

**Comment by me-no-dev** [comment]
@IMAN4K sorry for the long delay! Thank you for those examples!

**Pull request merged**
