### PR TITLE
Support staging platform

### PR DESCRIPTION
**Pull request by andig**
Partial fix for https://github.com/platformio/platformio-core/issues/1170

Would be great if this could then be released.

### CODE REVIEW

**Comment by me-no-dev** [comment]
done :) version bumped as well :) thanks!!!

**Comment by andig** [comment]
> version bumped as well

Mhhm. What's missing after the version bump:

	❯ pio lib update
	Library Storage: /Users/andig/Documents/htdocs/vzero/.piolibdeps
	Updating Adafruit Unified Sensor         @ 1.0.2          [Up-to-date]
	Updating ArduinoJson                     @ 5.11.2         [Up-to-date]
	Updating AsyncTCP                        @ a1a184a        [Up-to-date]
	Updating AsyncTCP                        @ 1.0.0          [Up-to-date]
	Updating DHT sensor library              @ 1.3.0          [Up-to-date]
	Updating DNSServer                       @ 9113193        [Up-to-date]
	Updating DallasTemperature               @ 3.7.7          [Up-to-date]
	Updating ESP Async WebServer             @ 8604f67        [Up-to-date]
	Updating ESPAsyncTCP                     @ 1.1.1          [Up-to-date]
	Updating OneWire                         @ 2.3.2          [Up-to-date]

`library.properties` which still has 1.1.0?

**Comment by me-no-dev** [comment]
I dont think that pio reads library.properties

**Comment by andig** [comment]
> I dont think that pio reads library.properties

I don't think either but it's still sitting at 1.1.1 for me. Confusing...

**Comment by me-no-dev** [comment]
Probably takes some time to update

**Pull request merged**
