### PR TITLE
ESP32

### PR DESCRIPTION
**Pull request by camilorodegheri**
First version working with ESP32.
Only supports IPv4
Need to add #ifdef guards to make compatible with both Arduino ESP8266 and ESP32

### CODE REVIEW

**Comment by me-no-dev** [comment]
Getting this to really work on esp32 is quite more code demanding. As you wrote it it will run on the network thread and that will not do in reality, because you will quickly run out of memory in a web server lets say.

**Comment by camilorodegheri** [comment]
Sure, you're right. My major use case is running AsnycMQTT and Homie, but the library should be done in a way to serve all cases.

Do you recommend create a new thread to run the async? If you could provide some major directions I will use them to improve the code.

Best Regards

**Comment by timpur** [comment]
Did it work on homie ? (That's what I want also :P)

**Comment by me-no-dev** [comment]
Well, it's more than just spinning a thread :) status change events need to go first and even maybe cancel previous queued events, so lets say you do not answer to a packet on an already closed connection. All AsyncTCP and UDP clients need to be handled by that same thread, and things on UDP are a bit more complicated when it comes to multicasting and such, though I have advanced in that direction in some soon to be published code in IDF.

**Pull request closed without merging**
